# Generated by Django 3.0.3 on 2024-12-17 11:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('src', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='donor',
            table='Donors',
        ),
    ]
